demoYt3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('technicalCourses.urls')),
]

technicalCourses/urls.py
from django.urls import path
from . import views

app_name='technicalCourses'

urlpatterns = [
  path('', views.Courses, name='home-page'),
  path('<int:course_id>/', views.Detail, name='detail'),
  path('<int:course_id>/yourchoice/', views.YourChoice, name='yourchoice')
]

technicalCourses/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.

class AllCourses(models.Model):
  coursename = models.CharField(max_length=200)
  insname = models.CharField(max_length=200)
  startedfrom = models.DateTimeField('Started from')

  def __str__(self):
    return self.coursename

  def was_published_recently(self):
    now = timezone.now()
    # return self.startedfrom >= timezone.now() - datetime.timedelta(days=1)
    return now - datetime.timedelta(days=1) <= self.startedfrom <= now

class Details(models.Model):
  course = models.ForeignKey(AllCourses, on_delete=models.CASCADE)
  # sp = models.CharField(max_length=500);
  # il = models.CharField(max_length=500);
  ct = models.CharField(max_length=500)
  your_choice = models.BooleanField(default=False)
  def __str__(self):
    return str(self.ct)

technicalCourses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import AllCourses, Details
from django.template import loader

def Courses(req):
  ac = AllCourses.objects.all()
  template = loader.get_template('./TechnicalCourses/courses.html')
  context = {
    'ac': ac,
  }
  return HttpResponse(template.render(context, req))

def Detail(req, course_id):
  # try:
  #   course = AllCourses.objects.get(pk=course_id)
  # except AllCourses.DoesNotExist:
  #   raise Http404('Course not available')
  # # return HttpResponse('<h2>These are the course details for course id: ' + str(course_id)+ '</h2>')
  # return render(req, './TechnicalCourses/detail.html', { 'course':course })
  course = get_object_or_404(AllCourses, pk=course_id)
  return render(req, './TechnicalCourses/detail.html', {
    'course': course
  })

def YourChoice(req, course_id):
  course = get_object_or_404(AllCourses, pk=course_id)
  try:
    selected_ct = course.details_set.get(pk=req.POST['choice'])
  except (KeyError, AllCourses.DoesNotExist):
    return render (req, 'AllCourses/detail.html', {
      'course': course,
      'error_message': 'Select a valid option '
    })
  else:
    selected_ct.your_choice=True
    selected_ct.save()
    return render(req, './TechnicalCourses/detail.html', {
      'course': course
    })


# Create your views here.

technicalCourses/templates/TechnicalCourses/courses.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
<!--  <title>Title</title>-->
  <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
    </div>
  </nav>
  <h1>Welcome !!!</h1>
  <ol>
    {% for x in ac %}
    <li>
      <a href="/{{x.id}}/">{{x.coursename}}</a>
    </li>
    {% endfor %}
  </ol>
</body>
</html>

technicalCourses/templates/TechnicalCourses/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Details</title>
</head>
<body>
  {% if course.pk is 1 %}
    <h1><a href="#">{{course}}</a></h1>
    <h2>{{course.insname}}</h2>
    <ul>
      {% for x in AllCourses.set.all %}
        <li>{ x.ct }</li>
      {% endfor %}
    </ul>
  {% elif course.pk is 2 %}
    <h1><a href="#">{{course}}</a></h1>
    <h2>{{course.insname}}</h2>
  {% else %}
    <h1><a href="#">{{course}}</a></h1>
    <h2>{{course.insname}}</h2>
  {% endif %}

  {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  <form
    action="{% url 'technicalCourses:yourchoice' course.id %}"
    method="POST"
  >
    {% csrf_token %}
    {% for choice in course.details_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">
      {{ choice.ct }}
    </label>
    <br>
    {% endfor %}
    <input type="submit" value="Submit">
  </form>
</body>
</html>